org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.java.installations.paths=/opt/jdks/java-8,/opt/jdks/java-17,/usr/lib/jvm/java-21-openjdk-amd64,/opt/jdks/java-25
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)
mod_id=typewriter_text
mod_name=Typewriter Text (\u6253\u5b57\u673a\u6587\u672c\u6837\u5f0f)
mod_license=All Rights Reserved
mod_version=1.0.0-r9
mod_group_id=cn.blockforge.generated.typewritertext
